create table if not exists public.love_sessions (
  id bigint generated by default as identity primary key,
  visit_id text not null,
  answers jsonb not null default '{}'::jsonb,
  score integer not null default 0,
  final_message text not null default '',
  created_at timestamptz not null default now()
);

create index if not exists idx_love_sessions_visit_id on public.love_sessions (visit_id);
create index if not exists idx_love_sessions_created_at on public.love_sessions (created_at desc);
